#@ load("@ytt:data", "data")
#@ load("ytt-helpers.star", "helpers")

#! Define-Groups
groups:
- name: release
  jobs:
  - unit-and-integration-tests
  - inigo-mysql-linux

resources:
  - name: ci
    type: git
    icon: source-branch
    source:
      branch: main
      uri: https://github.com/navinms711/wg-app-platform-runtime-ci


  - name: golang-release-latest
    type: git
    icon: tag-outline
    source:
      tag_filter: v*
      uri: https://github.com/bosh-packages/golang-release.git

  - name: repo
    type: git
    icon: source-branch
    source:
      branch: develop
      uri: https://github.com/navinms711/diego-release.git
      ignore_paths:
      - .github/
      - .gitignore
      - CODEOWNERS
      - LICENSE
      - NOTICE
      - README.md
      - docs/

  - name: image
    type: registry-image
    icon: docker
    source:                                        
      repository: us-central1-docker.pkg.dev/app-runtime-platform-wg/dockerhub-mirror/cloudfoundry/tas-runtime-build
      username: _json_key
      password: ((gcp-arp-artifact-registry-service-account-token))
      tag: latest

  - name: routing-release
    type: git
    icon: tag-outline
    source:
      branch: develop
      uri: https://github.com/cloudfoundry/routing-release.git

  - name: garden-runc-release
    type: git
    icon: source-branch
    source:
      branch: develop
      uri: https://github.com/cloudfoundry/garden-runc-release.git


  - name: diego-inigo-ci-rootfs
    type: docker-image
    icon: docker
    source:
      repository: us-central1-docker.pkg.dev/app-runtime-platform-wg/dockerhub-mirror/cloudfoundry/diego-inigo-ci-rootfs
      tag: latest
      username: _json_key
      password: ((gcp-arp-artifact-registry-service-account-token))
jobs:
  #@ for db in data.values.inigo_db_flavors:
  - name: #@ "inigo-{}-linux".format(db.value)
    serial: true
    plan:
    - in_parallel:
      - get: ci
      - get: repo
        trigger: true
      - get: image
      - get: package-release
        resource: golang-release-latest
      - get: garden-runc-release
      - get: routing-release
      - get: diego-inigo-ci-rootfs
        params:
          rootfs: true
    - in_parallel:
      - do:
        - task: determine-image-tag
          image: image
          file: ci/shared/tasks/determine-image-tag/linux.yml
        - load_var: image_tag
          file: determined-image-tag/tag
      - do:
        - task: #@ "determine-image-tag-{}".format(db.image)
          image: image
          file: ci/shared/tasks/determine-image-tag/linux.yml
          output_mapping:
            determined-image-tag: #@ "determined-image-tag-{}".format(db.image)
          params:
            IMAGE: #@ "cloudfoundry/tas-runtime-{}".format(db.image)
        - load_var: #@ "image_tag_{}".format(db.image.replace("-", "_").replace(".", "_"))
          file: #@ "determined-image-tag-{}/tag".format(db.image)
    - in_parallel:
      - task: build-binaries-for-diego-release-linux
        file: ci/shared/tasks/build-binaries/linux.yml
        output_mapping:
          built-binaries: diego-release-linux-built-binaries
        params:
          DEFAULT_PARAMS: "ci/diego-release/default-params/build-binaries/linux.yml"
        vars:
          image_repository: cloudfoundry/tas-runtime-build
          image_password: ((gcp-arp-artifact-registry-service-account-token))
          image_tag: ((.:image_tag))
      - task: build-binaries-for-garden-runc-release-linux
        file: ci/shared/tasks/build-binaries/linux.yml
        input_mapping:
          repo: garden-runc-release
        output_mapping:
          built-binaries: garden-runc-release-linux-built-binaries
        params:
          DEFAULT_PARAMS: "ci/garden-runc-release/default-params/build-binaries/linux.yml"
        vars:
          image_repository: cloudfoundry/tas-runtime-build
          image_password: ((gcp-arp-artifact-registry-service-account-token))
          image_tag: ((.:image_tag))
    - task: combine-built-binaries
      file: ci/shared/tasks/combine-assets/linux.yml
      image: image
      input_mapping:
        input-01: diego-release-linux-built-binaries
        input-02: garden-runc-release-linux-built-binaries
      output_mapping:
        combined-assets: built-binaries
      params:
        COPY_ACTIONS: |
          {input-01/*,combined-assets}
          {input-02/*,combined-assets}
    - do:
      - task: #@ "start-diego-{}-workers".format(db.value)
        image: image
        file: ci/shared/tasks/bosh-start/linux.yml
        params:
          DEPLOYMENT: #@ "diego-worker-{}".format(db.value)
          INSTANCE_GROUP: worker
          BOSH_CREDS: ((bosh-concourse-credentials/env_vars))
      - task: #@ "inigo-{}-linux".format(db.value)
        file: ci/shared/tasks/run-bin-test/linux.yml
        attempts: 3
        tags: #@ [ "diego-{}".format(db.value) ]
        privileged: true
        input_mapping:
          built-binaries: built-binaries
          input-01: routing-release
          input-02: garden-runc-release
          input-03: diego-inigo-ci-rootfs
        vars:
          image_repository: #@ "cloudfoundry/tas-runtime-{}".format(db.image)
          image_password: ((gcp-arp-artifact-registry-service-account-token))
          image_tag: #@ "((.:image_tag_{}))".format(db.image.replace("-", "_").replace(".", "_"))
        params:
          DIR: src/code.cloudfoundry.org/inigo
          DB: #@ db.value
          FLAGS: |
            --keep-going
            --trace
            -r
            --fail-on-pending
            --randomize-all
            --nodes=4
            --race
            --flake-attempts=3
          ENVS: |
            INIGO_ECR_AWS_ACCESS_KEY_ID=((aws-ecr-diego-docker-app/access-key-id))
            INIGO_ECR_AWS_SECRET_ACCESS_KEY=((aws-ecr-diego-docker-app/secret-access-key))
            INIGO_ECR_IMAGE_REF=((aws-ecr-diego-docker-app/ref))
            INIGO_ECR_IMAGE_ROOTFS_PATH=((aws-ecr-diego-docker-app/uri))
            INIGO_ECR_IMAGE_URI=((aws-ecr-diego-docker-app/uri))
            ROUTING_RELEASE_PATH=$PWD/input-01
            GARDEN_RUNC_RELEASE_PATH=$PWD/input-02
            DIEGO_RELEASE_PATH=$PWD/repo
            GARDEN_TEST_ROOTFS=$PWD/input-03/rootfs.tar
            DB_USER=root
            DB_PASSWORD=password
      ensure:
        task: #@ "stop-diego-{}-workers".format(db.value)
        image: image
        file: ci/shared/tasks/bosh-stop/linux.yml
        params:
          DEPLOYMENT: #@ "diego-worker-{}".format(db.value)
          INSTANCE_GROUP: worker
          BOSH_CREDS: ((bosh-concourse-credentials/env_vars))
  #@ end

  - name: unit-and-integration-tests
    serial: true
    serial_groups: [ diego-windows-worker ]
    plan:
    - in_parallel:
      - get: ci
      - get: repo
        trigger: true
      - get: image
      - get: package-release
        resource: golang-release-latest
    - in_parallel:
      - do:
        - task: determine-image-tag
          image: image
          file: ci/shared/tasks/determine-image-tag/linux.yml
        - load_var: image_tag
          file: determined-image-tag/tag
  #@ for db in data.values.db_flavors:
      - do:
        - task: #@ "determine-image-tag-{}".format(db.image)
          image: image
          file: ci/shared/tasks/determine-image-tag/linux.yml
          output_mapping:
            determined-image-tag: #@ "determined-image-tag-{}".format(db.image)
          params:
            IMAGE: #@ "cloudfoundry/tas-runtime-{}".format(db.image)
        - load_var: #@ "image_tag_{}".format(db.image.replace("-", "_").replace(".", "_"))
          file: #@ "determined-image-tag-{}/tag".format(db.image)
  #@ end
    - task: start-diego-windows-workers
      image: image
      file: ci/shared/tasks/bosh-start/linux.yml
      params:
        DEPLOYMENT: diego-worker-windows
        INSTANCE_GROUP: windows-worker
        BOSH_CREDS: ((bosh-concourse-credentials/env_vars))
    - in_parallel:
      - task: build-binaries-for-linux
        file: ci/shared/tasks/build-binaries/linux.yml
        output_mapping:
          built-binaries: linux-built-binaries
        image: image
        params:
          DEFAULT_PARAMS: "ci/diego-release/default-params/build-binaries/linux.yml"
        vars:
          image_repository: cloudfoundry/tas-runtime-build
          image_password: ((gcp-arp-artifact-registry-service-account-token))
          image_tag: ((.:image_tag))
      - task: build-binaries-for-windows
        tags: [ diego-windows ]
        file: ci/shared/tasks/build-binaries/windows.yml
        output_mapping:
          built-binaries: windows-built-binaries
        params:
          DEFAULT_PARAMS: "ci/diego-release/default-params/build-binaries/windows.yml"
    - in_parallel:
  #@ for package in helpers.packages_with_configure_db(data.values.internal_repos):
  #@ for db in data.values.db_flavors:
      - task: #@ "{}-{}-linux".format(package.name,db.image)
        file: ci/shared/tasks/run-bin-test/linux.yml
        privileged: #@ helpers.privileged(package)
        attempts: 3
        input_mapping:
          built-binaries: linux-built-binaries
        vars:
          image_repository: #@ "cloudfoundry/tas-runtime-{}".format(db.image)
          image_password: ((gcp-arp-artifact-registry-service-account-token))
          image_tag: #@ "((.:image_tag_{}))".format(db.image.replace("-", "_").replace(".", "_"))
        params:
          DIR: #@ "src/code.cloudfoundry.org/{}".format(package.name)
          DB: #@ db.value
          DEFAULT_PARAMS: "ci/diego-release/default-params/run-bin-test/linux.yml"
  #@ end
  #@ if helpers.on_windows(package):
      - task: #@ "{}-mysql-windows".format(package.name)
        file: ci/shared/tasks/run-bin-test/windows.yml
        tags: [ diego-windows ]
        privileged: true #! all windows test with DB required elavated
        attempts: 3
        input_mapping:
          built-binaries: windows-built-binaries
        params:
          DIR: #@ "src/code.cloudfoundry.org/{}".format(package.name)
          DB: mysql
          DEFAULT_PARAMS: "ci/diego-release/default-params/run-bin-test/windows.yml"
  #@ end
  #@ end
    - in_parallel:
  #@ for package in helpers.packages_without_configure_db(data.values.internal_repos):
      - task: #@ "{}-linux".format(package.name)
        file: ci/shared/tasks/run-bin-test/linux.yml
        privileged: #@ helpers.privileged(package)
        attempts: 3
        input_mapping:
          built-binaries: linux-built-binaries
        vars:
          image_repository: cloudfoundry/tas-runtime-build
          image_password: ((gcp-arp-artifact-registry-service-account-token))
          image_tag: ((.:image_tag))
        params:
          DIR: #@ "src/code.cloudfoundry.org/{}".format(package.name)
  #@ if helpers.on_windows(package):
      - task: #@ "{}-windows".format(package.name)
        file: ci/shared/tasks/run-bin-test/windows.yml
        tags: [ diego-windows ]
        privileged: true #! for windows test 
        attempts: 3
        input_mapping:
          built-binaries: windows-built-binaries
        params:
          DIR: #@ "src/code.cloudfoundry.org/{}".format(package.name)
  #@ end
  #@ end
